# Generated by Django 5.2.10 on 2026-01-31 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('is_fixed', models.BooleanField(default=False)),
                ('category', models.CharField(choices=[('exercise', '運動'), ('habit', '生活習慣'), ('heavy', '重め')], max_length=20)),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
