# Generated by Django 5.2.10 on 2026-01-31 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='google_fit_token',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='google_fit_credentials',
            field=models.JSONField(blank=True, help_text='GoogleFitの認証情報の保存用', null=True),
        ),
    ]
