# Generated by Django 5.2.10 on 2026-01-31 01:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
        ('users', '0002_remove_userprofile_google_fit_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='weekly_heavy_goal',
            field=models.ForeignKey(blank=True, limit_choices_to={'category': 'heavy'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users_with_this_goal', to='tasks.task'),
        ),
    ]
