# Generated by Django 5.2.10 on 2026-02-02 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userprofile_weekly_heavy_goal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='daily_step_goal',
            field=models.IntegerField(default=10000),
        ),
    ]
