# Generated by Django 5.2.10 on 2026-02-03 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('histories', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stepcount',
            name='calculated_value',
        ),
    ]
